# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-03-20 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hostname',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
